name: Build/Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    permissions:
      contents: write
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-22.04]

    steps:
      - name: Check out git repository
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Install Linux dependencies
        if: matrix.os == 'ubuntu-22.04'
        run: sudo apt-get update && sudo apt-get install -y libarchive-tools fakeroot libfuse2 squashfs-tools fuse

      - name: Build (Windows)
        if: matrix.os == 'windows-latest'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pnpm run build
          pnpm exec electron-builder --win

      - name: Upload Windows Release
        if: matrix.os == 'windows-latest'
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build (macOS)
        if: matrix.os == 'macos-latest'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pnpm run build
          pnpm exec electron-builder --mac

      - name: Upload macOS Release
        if: matrix.os == 'macos-latest'
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*.dmg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build (Linux)
        if: matrix.os == 'ubuntu-22.04'
        env:
          APPIMAGE_EXTRACT_AND_RUN: 1
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pnpm run build
          pnpm exec electron-builder --linux

      - name: Upload Linux Release
        if: matrix.os == 'ubuntu-22.04'
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/*.AppImage
            dist/*.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
